name: muserpol_app
description: Aplicación móvil de trámites de MUSERPOL.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 6.0.12
  maps_launcher: 2.0.1
  http: 0.13.4
  flutter_dotenv: 5.0.2
  shared_preferences: 2.0.8
  path_provider: 2.0.6
  dropdown_date_picker: 0.1.1+2
  wakelock: 0.5.6
  camerawesome: 0.3.0+1
  disk_space: 0.2.1
  open_file: 3.2.1
  permission_handler: 6.1.3
  device_info_plus: 3.1.1
  connectivity_plus: 2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
