name: muserpol_app
description: Aplicación móvil de trámites de MUSERPOL.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ">=0.19.2+1"
  url_launcher: ^5.7.10
  maps_launcher: ^1.2.2+2
  http: ^0.12.2
  flutter_dotenv: ^2.1.0
  shared_preferences: ^0.5.12+4
  platform_device_id: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: 'fonts/roboto/Roboto-ThinItalic.ttf'
        - asset: 'fonts/roboto/Roboto-Thin.ttf'
        - asset: 'fonts/roboto/Roboto-Regular.ttf'
        - asset: 'fonts/roboto/Roboto-MediumItalic.ttf'
        - asset: 'fonts/roboto/Roboto-Medium.ttf'
        - asset: 'fonts/roboto/Roboto-LightItalic.ttf'
        - asset: 'fonts/roboto/Roboto-Light.ttf'
        - asset: 'fonts/roboto/Roboto-Italic.ttf'
        - asset: 'fonts/roboto/Roboto-BoldItalic.ttf'
        - asset: 'fonts/roboto/Roboto-Bold.ttf'
        - asset: 'fonts/roboto/Roboto-BlackItalic.ttf'
        - asset: 'fonts/roboto/Roboto-Black.ttf'