name: muserpol_app
description: Aplicación móvil de trámites de MUSERPOL.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 6.0.6
  maps_launcher: 2.0.0
  http: 0.13.3
  flutter_dotenv: 5.0.0
  shared_preferences: 2.0.6
  unique_id: 0.0.2
  path_provider: 2.0.2
  dropdown_date_picker: 0.1.1+2
  wakelock: 0.5.2
  camerawesome: 0.3.0+1
  disk_space: 0.1.1
  open_file: 3.2.1
  permission_handler: 6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
